license="The MIT License (MIT)"
modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="genericskilllib"
version="${file.jarVersion}"
displayName="Generic Skill Lib"
authors="Arekkuusu"
displayURL="https://www.curseforge.com/minecraft/mc-mods/genericskilllib"
logoFile="logo.png"
description="Library mod for basic skill functionality"